name: Deploy Firebase Functions on push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create .env file
        run: |
          cd functions
          echo "TARGET_BUCKET=${{ vars.TARGET_BUCKET }}" > .env

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Deploy Firebase Functions
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"
          firebase deploy --only functions --project=damatest-f8061